/**
 * Daily Digest articles. Body convention (rendered by components/daily-digest/ArticleBody):
 * - Section title: a paragraph starting with "## " → <h2>; "### " → <h3>.
 * - Bulleted list: consecutive paragraphs starting with "- " (or "* ").
 * - Numbered list: consecutive paragraphs starting with "1. " (or "1) ").
 * - Anything else is a normal paragraph. One string may also hold several lines split by "\n".
 * Example:
 *   paragraphs: ["## Why it matters", "Short intro.", "- first point", "- second point", "1. Do this", "2. Then this"]
 * Optional: `sections: [{ heading: "Why it matters", body: ["Short intro.", "- first point"] }]`
 * renders after `paragraphs`, each heading as <h2>.
 */
export type PostTag = "Technique" | "Deep dive" | "Essay";

/**
 * Hero art (SPEC §11). `alt` is required: one plain sentence describing the picture (final copy, used exactly).
 * Two shapes:
 * - `{ src, cardSrc, alt }`: Brand Creator files under public/art/digest/: `src` is the 1600×900 (16:9) article hero,
 *   `cardSrc` the 1200×900 (4:3) centre-safe crop used by index / Next article / homepage cards.
 * - `{ image, alt }` (legacy): a base name under public/art/ with `<image>-1280.webp` + `<image>-640.webp` (16:9);
 *   cards crop it to 4:3 with object-fit.
 * Leave `hero` out and the article uses the shared fallback tile (lib/daily-digest/meta.ts → FALLBACK_HERO).
 */
export type PostHero = { image: string; alt: string } | { src: string; cardSrc: string; alt: string };

/**
 * Pull quote (SPEC §8, v1.2): `text` must be a verbatim line from this article's body (the test suite checks it).
 * It renders right after the paragraph that contains it. `cite` is shown in meta type under the quote.
 */
export type PostPullQuote = { text: string; cite?: string };

export type Post = {
  slug: string;
  title: string;
  dek: string;
  date: string;
  /** Index + article meta tag. Omitted = "Technique". */
  tag?: PostTag;
  /** Per-article art (hero + card crop + alt). Omitted = fallback tile. */
  hero?: PostHero;
  /** Optional shorter one-line dek for index / Next article cards. Omitted = `dek`. */
  cardDek?: string;
  pullQuote?: PostPullQuote;
  sourceNote?: string;
  paragraphs: string[];
  sections?: { heading: string; body: string[] }[];
};

export const posts: Post[] = [
  {
    slug: "reuse-the-same-key-when-a-tool-retries",
    title: "Reuse the same key when a tool retries",
    dek: "Prevents double-charges on payment or deploy retries.",
    cardDek: "Reuse one request ID on retries so payments and deploys don't run twice.",
    hero: {
      src: "/art/digest/reuse-the-same-key-when-a-tool-retries.webp",
      cardSrc: "/art/digest/reuse-the-same-key-when-a-tool-retries-card.webp",
      alt: "A stone bottle sealed with a lime-green cork, and a second black cork of the same shape lying beside it with nowhere to go.",
    },
    date: "2026-09-16",
    paragraphs: [
      "## The technique",
      "Agents that retry payments, posts, or deploys after a timeout often mint a new key each try. That creates duplicate side effects. A gate that requires a stable key per logical order blocks release when retries would double-charge.",
      "## How it was tested",
      "Offline structural sim (no live model): 5 drop_ack charge episodes. Stable keys: 0 I1 violations (one charge each). Fresh UUID keys: 5 of 5 double-charges; gate blocked release on that pattern.",
    ],
  },
  {
    slug: "require-held-out-lift-before-shipping-harness-edits",
    title: "Require held-out lift before shipping harness edits",
    dek: "Stops train-only tweaks that fail on new cases.",
    cardDek: "Only ship a setup tweak if it also helps on cases it wasn't tuned on.",
    hero: {
      src: "/art/digest/require-held-out-lift-before-shipping-harness-edits.webp",
      cardSrc: "/art/digest/require-held-out-lift-before-shipping-harness-edits-card.webp",
      alt: "Two stone water tanks, one calm and one choppy, with a small black sailboat and lime-green sail in the choppy one.",
    },
    date: "2026-09-16",
    paragraphs: [
      "## The technique",
      "Harness edits that look great on the training set can collapse on held-out cases. Selecting by train lift alone ships the brittle option. A gate that requires held-out mean lift and non-negative worst-case held-out delta picks the version that transfers.",
      "## How it was tested",
      "Offline structural sim (no live model): two mock harnesses A (train overfit) vs B (transfers). Train-only selection shipped A (held lift −0.15). Held-out + worst-Δ gate shipped B (held lift +0.143).",
    ],
  },
  {
    slug: "load-only-the-tools-this-turn-needs",
    title: "Load only the tools this turn needs",
    dek: "Cuts prompt size without losing the needed tool.",
    cardDek: "Give the agent only the tools this turn needs, so prompts stay small.",
    hero: {
      src: "/art/digest/load-only-the-tools-this-turn-needs.webp",
      cardSrc: "/art/digest/load-only-the-tools-this-turn-needs-card.webp",
      alt: "A large closed stone toolbox beside a small open tray that holds a single lime-green screwdriver.",
    },
    date: "2026-09-16",
    paragraphs: [
      "## The technique",
      "Large tool catalogs burn tokens when every schema is always loaded. Deferred load via keyword search keeps the needed tool available while cutting prompt size. A bad query negative control confirms the search can miss when it should.",
      "## How it was tested",
      "Offline structural sim (no live model): 8-tool catalog. Naive load-all used 1530 mock tokens; tool-search top path used 220 (−85.6%) with needed tool still available; bad query correctly left needed tool unavailable.",
    ],
  },
  {
    slug: "refuse-answers-that-dont-match-tool-results",
    title: "Refuse answers that don’t match tool results",
    dek: "Stops invented “CI green” or fake search hits from shipping as done.",
    cardDek: "Catch answers that claim results the tools never returned.",
    hero: {
      src: "/art/digest/refuse-answers-that-dont-match-tool-results.webp",
      cardSrc: "/art/digest/refuse-answers-that-dont-match-tool-results-card.webp",
      alt: "A black star-shaped cookie cutter beside a round stone cookie that doesn't match it, with one lime-green sprinkle on top.",
    },
    date: "2026-09-23",
    paragraphs: [
      "## The technique",
      "Agents sometimes invent success: green CI when the log failed, search hits that were never returned. An alignment gate compares the final claim to tool facts and refuses stop when they disagree, so misaligned answers don't ship as done.",
      "## How it was tested",
      "Offline structural sim (no live model): 8 alignment cases. Gate matched the expected allow/refuse decision on all 8 and caught 4 cases a naive “always accept claim” path would have slipped.",
    ],
  },
  {
    slug: "bind-every-claim-to-a-real-citation",
    title: "Bind every claim to a real citation",
    dek: "Blocks unsupported or mis-cited final answers.",
    cardDek: "Tie every claim to a real source, or leave it out.",
    hero: {
      src: "/art/digest/bind-every-claim-to-a-real-citation.webp",
      cardSrc: "/art/digest/bind-every-claim-to-a-real-citation-card.webp",
      alt: "Three stone balloons, each tied by a black string to its own small weight, with one weight in lime-green.",
    },
    date: "2026-09-23",
    paragraphs: [
      "## The technique",
      "Final answers often invent PR states, CI outcomes, or cite the wrong tool id. Binding each claim to a supporting citation and checking support blocks unsupported or mis-cited answers before they leave the harness.",
      "## How it was tested",
      "Offline structural sim (no live model): 7 citation cases. Gate matched expected allow/refuse on all 7 and blocked 5 bad answers a baseline would have accepted (invented state, missing cite, fake tool id, wrong cite, partial-bad).",
    ],
  },
  {
    slug: "compare-models-only-under-a-locked-setup",
    title: "Compare models only under a locked setup",
    dek: "Stops harness help from looking like model skill.",
    cardDek: "Test every model on the same setup, so the score reflects the model.",
    hero: {
      src: "/art/digest/compare-models-only-under-a-locked-setup.webp",
      cardSrc: "/art/digest/compare-models-only-under-a-locked-setup-card.webp",
      alt: "Three different toy race cars on identical stone ramps, with one lime-green ribbon stretched across all three.",
    },
    date: "2026-09-23",
    paragraphs: [
      "## The technique",
      "Naive “best score per model across any harness” mixes model skill with harness help. A locked factorial grid (model × harness) shows rank reversals and how much variance comes from the harness, so you don't pick a model on an undisclosed setup.",
      "## How it was tested",
      "Offline structural sim (no live model): 3 models × 3 harnesses. Naive best-per-model rank differed from locked ranks; harness share of explained variance ~0.95; 3 pairwise rank reversals; 6/6 structural checks passed (reject undisclosed harness).",
    ],
  },
  {
    slug: "block-done-if-code-changed-after-tests",
    title: "Block “done” if code changed after tests",
    dek: "Stops untested edits from being reported as finished.",
    cardDek: "Don't call it done if code changed after the last test run.",
    hero: {
      src: "/art/digest/block-done-if-code-changed-after-tests.webp",
      cardSrc: "/art/digest/block-done-if-code-changed-after-tests-card.webp",
      alt: "A stone jar with its lid lifted, and a lime-green seal strip broken and hanging loose from the rim.",
    },
    date: "2026-09-24",
    paragraphs: [
      "## The technique",
      "Agents sometimes edit code after the last green test, then claim the work is finished. A stop gate that asks “did anything change after the last passing test?” refuses stop when the answer is yes, so untested edits don't ship as done.",
      "## How it was tested",
      "Offline structural sim (no live model): 8 freshness cases. Gate matched the expected allow/refuse decision on all 8 and caught 5 cases where a naive “always allow done” would have stopped after stale edits.",
    ],
  },
  {
    slug: "trim-long-logs-from-both-ends",
    title: "Trim long logs from both ends",
    dek: "Keeps the error codes the model needs when logs get cut.",
    cardDek: "Cut long logs from both ends so the error lines survive.",
    hero: {
      src: "/art/digest/trim-long-logs-from-both-ends.webp",
      cardSrc: "/art/digest/trim-long-logs-from-both-ends-card.webp",
      alt: "Two lengths of black beads with the middle cut away, four grey beads set aside, and one lime-green bead between them.",
    },
    date: "2026-09-24",
    paragraphs: [
      "## The technique",
      "Huge tool logs get cut to fit the context window. Cutting only the start throws away useful error codes and cursors in the middle or end. Keeping a bit of the start, a bit of the end, plus lines with critical keywords preserves the facts the model needs under a tight budget.",
      "## How it was tested",
      "Offline structural sim (no live model): one oversized tool payload (~782 tok) under a ~120 tok budget. Head-only truncation kept 2 of 6 critical keys. Budgeted head+tail+keyword keep kept all 6 of 6 under the cap.",
    ],
  },
  {
    slug: "prove-it-before-irreversible-actions",
    title: "Prove it before irreversible actions",
    dek: "Blocks send, delete, and force-push without fresh proof.",
    cardDek: "Get fresh proof before a send, delete, or overwrite you can't undo.",
    hero: {
      src: "/art/digest/prove-it-before-irreversible-actions.webp",
      cardSrc: "/art/digest/prove-it-before-irreversible-actions-card.webp",
      alt: "A black push button under a frosted hinged safety cover, held shut by a small lime-green latch.",
    },
    date: "2026-09-25",
    paragraphs: [
      "## The technique",
      "Agents sometimes skip the safety step and just act — especially when a prior turn “already checked.” For irreversible moves (send, delete, force-push, trade), the harness must demand a fresh approval or a matching dry-run for that exact action and target before the tool runs. Wrong target or stale proof still blocks.",
      "## How it was tested",
      "Offline structural sim (no live model): 10 preflight cases. Gate matched all 10 allow/refuse decisions; caught 5 cases a naive always-allow path would have slipped (missing proof, stale approval, wrong target, failed dry-run).",
    ],
  },
  {
    slug: "tell-failed-tools-what-to-try-next",
    title: "Tell failed tools what to try next",
    dek: "Turns vague errors into a short list of safe fixes.",
    cardDek: "Turn vague errors into a short list of safe next steps.",
    hero: {
      src: "/art/digest/tell-failed-tools-what-to-try-next.webp",
      cardSrc: "/art/digest/tell-failed-tools-what-to-try-next-card.webp",
      alt: "A stone board with one empty jigsaw slot, a rejected black piece beside it, and three spare pieces, one lime-green.",
    },
    date: "2026-09-25",
    paragraphs: [
      "## The technique",
      "Raw error text is hard for an agent to repair from. Feedback that names the failure location, the observed value, and a short list of admissible alternatives lets the next attempt pick a valid fix instead of guessing. Same idea as structured verifier feedback in recent agent-loop research.",
      "## How it was tested",
      "Offline structural sim (no live model): 8 repair cases. Structured feedback recovered a valid alternative in 7 of 8; raw-message repair recovered only 3 of 8. All 6 structural checks passed.",
    ],
  },
  {
    slug: "dont-blind-retry-sends-or-charges",
    title: "Don't blind-retry sends or charges",
    dek: "Stops duplicate emails and double charges after timeouts.",
    cardDek: "Check before retrying so a timeout doesn't send or charge twice.",
    hero: {
      src: "/art/digest/dont-blind-retry-sends-or-charges.webp",
      cardSrc: "/art/digest/dont-blind-retry-sends-or-charges-card.webp",
      alt: "A stone mailbox on a short black post with its door shut and a small lime-green flag raised on its side.",
    },
    date: "2026-09-25",
    paragraphs: [
      "## The technique",
      "Blind retries treat every failure like a safe read. Sends, charges, and comments can commit even when the client times out. Classify the op: reads may retry; side-effecting ops retry only when a reconcile check proves not_committed, and fail closed when the commit state is unknown.",
      "## How it was tested",
      "Offline structural sim (no live model): 10 retry cases. Gate matched all 10; blocked 4 blind-retry slips (unknown or already-committed side effects) while still allowing reconciled not_committed retries and all reads.",
    ],
  },
  {
    slug: "laya-ai-deep-dive",
    title: "Laya AI deep dive — open typed decisions, not a chat model",
    dek: "Full board brief: Laya is ConvAI’s open System-1 decision model (not the community mirror). How to run it, when it fits. Cross-links Jev.",
    cardDek: "What Laya is, how to run it, and when it beats a chat model.",
    hero: {
      src: "/art/digest/laya-ai-deep-dive.webp",
      cardSrc: "/art/digest/laya-ai-deep-dive-card.webp",
      alt: "A clear marble run that splits into three chutes ending in cups, with one lime-green marble rolling down.",
    },
    date: "2026-09-25",
    tag: "Deep dive",
    paragraphs: [
      "Board brief on Laya: what it actually is, how to run it, and when it helps. Companion piece: System One / Jev by TypeSafe AI.",
      "## What it is (verified)",
      "Laya is an open-weight, non-autoregressive decision model from ConvAI Innovations (private limited company, Kasaragod, Kerala, India). You give it a state (text, email, ticket, or JSON) plus typed questions; it returns structured answers with probabilities in one forward pass. It does not generate free-form text, so there is nothing to parse and no chat-style hallucination path for the label itself.",
      "Three decision primitives (same job shape as TypeSafe Jev):",
      "- choice — pick one named option (e.g. billing vs technical) with a probability distribution",
      "- score — place the input on an ordered rubric (e.g. urgency 0–3)",
      "- noul — calibrated P(true) for a yes/no proposition (e.g. refund requested, churn risk)",
      "Three published checkpoints (Apache 2.0) on Hugging Face under convaiinnovations/laya:",
      "- laya — ModernBERT-large backbone, ~421M params, 512 context — English triage / guardrails",
      "- laya-multilingual — mmBERT-base backbone, ~322M params, 1024 context (encoder up to 8k) — 100+ languages",
      "- laya-typed-decisions — ModernBERT-large backbone, ~421M params, 1024 context — fine-tuned for typed-decision workflows (upstream reports 0.766 accuracy on their 2,000-decision bench)",
      "Install surface (verified today): pip install laya — PyPI 0.3.20. Upstream quickstart: from laya import Router, then router.predict(state, questions), with optional Router(preload=True). Self-host HTTP via laya[serve] / laya-serve claims a Jev-compatible POST /v1/systemone shape (compatibility claim from upstream; not independently re-tested here).",
      "Company (verified / public records): CONVAI INNOVATIONS PRIVATE LIMITED, CIN U72900KL2021PTC070857, incorporated 11 Sep 2021, ROC Ernakulam. Directors listed in MCA aggregators: Nandakishor Mukkunnoth, Anjali Mukkunnoth, Mukkunnoth Archana. Authorised / paid-up capital shown as ₹100,000 — small private company. Company site positions broader products (Nadhi co-scientist / audit tooling, AI4Cardio) alongside Laya. Tracxn lists incubator / institutional ties (Kerala Startup Mission, IPTIF) and “funding raised” without a disclosed round size — treat amount as unverified.",
      "## Important: laya-ai.com is not the official product site",
      "https://laya-ai.com is an independent community resource. Its own FAQ states it is not affiliated with ConvAI Innovations. Useful for orientation and demos; treat marketing copy there as secondary.",
      "### Prefer these primary sources:",
      "- Official write-up: https://laya.convaiinnovations.com/",
      "- Weights / model card: https://huggingface.co/convaiinnovations/laya",
      "- Code: https://github.com/NandhaKishorM/laya",
      "- Company about: https://convaiinnovations.com/about",
      "- Live demo Space: https://huggingface.co/spaces/convaiinnovations/laya-demo",
      "GitHub popularity (verified via GitHub API, Fri Sep 25 ET): NandhaKishorM/laya ≈ 24.5k stars, ≈ 2.1k forks, created 18 Sep 2026, license Apache-2.0. Star count is real and still moving fast; it is not by itself proof of production fitness.",
      "## How to use it",
      "Typical path for an eng team:",
      "1. Install Python 3.10+ and pip install laya (add extras only if needed: serve / mcp / langchain / onnx).",
      "2. Build a small question schema with choice / score / noul for your workflow (keep choice sets under ~20 options at default settings — upstream documents degradation above that).",
      "3. Call Router().predict(state, questions) — or Router(preload=True) in a long-lived server so language switches do not pay multi-second cold loads.",
      "4. Gate automation on confidence and your own thresholds; escalate uncertain cases to a larger LLM or a human.",
      "5. For production quality: fine-tune on your labeled decisions and refit temperature calibration on held-out domain data. Upstream is explicit that base checkpoints are near chance on their typed-decisions bench zero-shot; the 0.766 figure belongs to the fine-tuned checkpoint.",
      "Self-host options called out upstream: Python SDK, laya-serve HTTP, Docker / CLI notes in docs, community MLX / ONNX / JS ports (community ≠ official support).",
      "## When it is useful",
      "### Good fit",
      "- High-volume routing / triage (support queues, email department, agent/model router)",
      "- Guardrails before a generative model runs (jailbreak / policy / abuse flags) when you want structured probs, not another essay",
      "- Risk / churn / phishing-style boolean scores you can threshold",
      "- Air-gapped or cost-sensitive stacks where a ~300–400M encoder on your GPU beats metered frontier calls for reflex decisions",
      "- Multilingual intake when Latin-script English models would quietly fail (upstream shows English checkpoint can be confidently wrong on non-Latin scripts — router exists for that reason)",
      "### Poor fit / caution",
      "- Anything that must write text (summaries, replies, code) — pair with a generator; Laya is not a chatbot",
      "- High-cardinality single-shot choice (>20–50 labels): upstream Banking77 stress shows sharp drop vs hosted Jev at default token budgets",
      "- Blind trust of zero-shot base weights on your domain without labels or calibration",
      "- Treating upstream vs-Jev tables as a controlled bake-off: Laya authors state they lacked TypeSafe API access and that sample sizes / prompts differ",
      "## Laya vs Jev (short)",
      "Same product category (System One-style typed decisions). Jev is TypeSafe’s hosted closed model (API, early access / paid metering). Laya is ConvAI’s open-weight Apache 2.0 alternative you self-host. See the companion digest on System One / Jev for the TypeSafe side.",
      "## Claims vs evidence",
      "### Stronger / source-backed",
      "- Open weights + Apache 2.0 code path exist (HF + GitHub + PyPI verified)",
      "- Product category is real and competitive with TypeSafe Jev",
      "- Upstream documents honest ceilings (cardinality, zero-shot weakness, calibration needs)",
      "### Weaker / treat as marketing or not independently verified here",
      "- Exact latency / accuracy deltas vs Jev on identical prompts (directional only)",
      "- Enterprise “commercial support / custom fine-tuning” pricing — mentioned on HF card; no public price sheet found",
      "- Any customer logos, ARR, or production SLAs — not verified",
      "Name collision risk: funding databases also mention unrelated “Laya Ai” entities (e.g. travel). For this product, stick to ConvAI Innovations / NandhaKishorM/laya / convaiinnovations/laya.",
      "## Bottom line",
      "Laya is a real open System-1 decision stack for structured choice / score / probability gates, not a chat model and not the community mirror site. Use it when you need fast typed decisions you can branch on in code; fine-tune and calibrate before trusting it.",
      "## Sources",
      "- Laya official write-up (ConvAI): https://laya.convaiinnovations.com/",
      "- Hugging Face — convaiinnovations/laya: https://huggingface.co/convaiinnovations/laya",
      "- GitHub — NandhaKishorM/laya: https://github.com/NandhaKishorM/laya",
      "- PyPI — laya 0.3.20: https://pypi.org/project/laya/",
      "- Community mirror (not affiliated) — laya-ai.com: https://laya-ai.com/",
      "- ConvAI Innovations — About: https://convaiinnovations.com/about",
      "- MCA / companydetails — Convai Innovations Pvt Ltd: https://www.companydetails.in/company/convai-innovations-private-limited",
      "- Tracxn — Convai Innovations (funding ties, amount undisclosed): https://tracxn.com/d/legal-entities/india/convai-innovations-private-limited/__W6wR3BMALR38rcaGCt1N9HFDIqCMkeigdjDhicJCqsU",
      "- The Left Shift — Laya HF trending coverage: https://www.theleftshift.com/an-indian-ai-model-that-doesnt-chat-claims-top-spot-on-hugging-face/",
      "- Companion — System One / Jev digest: /daily-digest/system-one-and-jev-deep-dive",
    ],
  },
  {
    slug: "system-one-and-jev-deep-dive",
    title: "System One & Jev — TypeSafe’s hosted typed-decision model",
    dek: "Full board brief on TypeSafe’s System One category and Jev (Almeida): how the API works, when it beats LLMs, vs open Laya.",
    cardDek: "How TypeSafe's hosted decision model works and when it beats a chat model.",
    hero: {
      src: "/art/digest/system-one-and-jev-deep-dive.webp",
      cardSrc: "/art/digest/system-one-and-jev-deep-dive-card.webp",
      alt: "A flat black block with a round opening on top and three small trays, one holding a lime-green disc.",
    },
    date: "2026-09-25",
    tag: "Deep dive",
    paragraphs: [
      "Board brief on TypeSafe AI’s System One category and flagship model Jev (Diogo Almeida / TypeSafe). Companion piece: open-weight Laya.",
      "## What it is (verified)",
      "TypeSafe AI is a San Francisco frontier lab building System One models: AI optimized for fast, typed decisions software can consume, not chat. The name nods to Kahneman’s fast System 1 thinking. Founded 2024; emerged from stealth 15 Sep 2026.",
      "Jev (after Jevons) is TypeSafe’s first public System One model. You send state (text or structured JSON) plus typed questions; Jev returns typed answers with probabilities / confidence. It does not generate strings — no free-form text, no parse step, schema violations described by TypeSafe as impossible by construction.",
      "Three primitives (docs + launch post):",
      "- choice — pick one option from criteria you define (docs: up to 255 options)",
      "- score — rate state on an ordered rubric (docs: 2–10 levels)",
      "- noul — P(true) for a yes/no proposition (0–1)",
      "Training claim (company): Reinforcement Learning for Calibrated Decisions (RLCD) — optimize for calibrated probabilities on System One tasks, not RLHF-style chat preference. Architecture claim: parallel sampler returns all question answers in one shot rather than autoregressive tokens.",
      "Team (company site): CEO Diogo Almeida (ex-OpenAI; company/press describe RLHF / InstructGPT / ChatGPT contributions; previously Google Brain); COO Sasha Sheng (ex-Meta/FAIR); CTO Erik Gafni (repeat founder; Invitae / Freenome background per company bio).",
      "Funding (press, Sep 15–16 2026): ~$40M seed led by DCVC (BusinessWire / SiliconANGLE). Forbes reported a ~$200M valuation citing a person familiar — treat valuation as reported, not company-confirmed in sources reviewed.",
      "## How to use it",
      "Access: Launch post opened early access / waitlist on 15 Sep 2026 at typesafe.ai. Third-party TechStrong (21 Sep) reported broader availability with a small usage credit — treat access tiers as moving; confirm live at console / waitlist rather than assuming open self-serve.",
      "### Docs / API (verified from docs.typesafe.ai):",
      "1. Get an API key (console once admitted).",
      "2. POST https://api.typesafe.ai/v1/systemone with Authorization: Bearer <API_KEY>.",
      "3. Body includes state, model (docs examples use jev-latest), and a questions map of typed items (choice / score / noul).",
      "4. Response returns answers under the same keys, plus usage token counts. Choice/score answers include probabilities and a derived confidence; noul returns a 0–1 probability.",
      "5. SDKs and an agent “skill” for coding agents are documented for wiring questions into app code.",
      "Design pattern TypeSafe pushes: keep control flow in your code; ask many narrow, independent questions in one call; compose probabilities with thresholds; escalate low-confidence cases to humans or slower LLMs. Jev is positioned as a smart if-statement / workflow primitive, not an agent loop.",
      "Pricing claims (company, as of launch materials / docs snippets): about $0.042 per million input tokens ($42 per billion); output tokens free. Homepage also markets large speed/cost multiples vs LLM workflows (e.g. ~194× faster / ~445× cheaper on their workflow evals). TypeSafe itself notes prices may be early and that long-term sustainability is unproven; SiliconANGLE notes those multiples are company tests and not independently verified.",
      "## When it is useful vs LLMs",
      "### Good fit",
      "- High-volume classify / route / score / detect steps inside production software",
      "- Guardrails / judges on LLM prompts, tool calls, or outputs when you need probs + latency, not another essay",
      "- Real-time UX paths where hundreds of ms matter",
      "- Map-reduce style feature extraction over large text corpora",
      "- Workflows where you already know the decision schema and want code to own branching",
      "### Poor fit / caution",
      "- Anything that must write text, code, or explanations — still need an LLM (or human)",
      "- Tasks needing long chain-of-thought as the product (System One is deliberately non-generative)",
      "- Blind trust of confidence without calibrating on your labels",
      "- Multimodal inputs today — docs state text / JSON only (no images/audio/video yet); English primary",
      "- Assuming “can’t hallucinate” means “can’t be wrong” — constrained types ≠ correct judgments; wrong-but-typed answers remain possible",
      "## Jev vs Laya (short)",
      "- Delivery: Jev = hosted API · Laya = open weights / self-host",
      "- License: Jev = closed · Laya = Apache 2.0",
      "- Interface: both use choice / score / noul",
      "- Cost: Jev ≈ $0.042/MTok input (company) · Laya = your GPU / ops",
      "- Where each leans: Jev claims stronger high-cardinality choice + managed latency · Laya leans local / air-gap, multilingual router, free weights",
      "- Company posture: TypeSafe = well-funded SF lab, early product · ConvAI = small Indian Pvt Ltd + viral open release",
      "They compete in the same category. Prefer Jev when you want a managed API and can accept vendor lock-in / waitlist. Prefer Laya when you need on-prem, offline, or zero per-token cost and will invest in fine-tune + calibration. Full Laya brief is the companion digest.",
      "## Claims vs evidence",
      "### Stronger / source-backed",
      "- Category pitch and API shape are documented (launch post + docs.typesafe.ai)",
      "- Seed financing coverage from multiple outlets (~$40M, DCVC-led)",
      "- Founder pedigree is publicly described by company and press",
      "- Pricing and latency claims are stated transparently by TypeSafe (even while noting possible subsidy)",
      "### Weaker / treat carefully",
      "- Workflow speed/cost multiples vs frontier LLMs — company evals; SiliconANGLE flags lack of independent verification",
      "- “Can’t hallucinate” marketing — means no free-text / type-safe outputs, not perfect accuracy",
      "- Valuation (~$200M) — Forbes via anonymous source",
      "- GA vs waitlist status — conflicting third-party reports within one week; verify live access yourself",
      "- Long-term unit economics of $0.042/MTok with free outputs — company says unproven",
      "## Bottom line",
      "System One / Jev is a serious attempt to make frontier-ish judgment a typed software primitive (fast, parallel, calibrated probs, no string gen). Use it for routing, scoring, detection, and LLM guardrails inside code you control. Keep generative LLMs for writing. Treat speed/cost banners as company-reported. Read the Laya companion before assuming TypeSafe owns the category alone.",
      "## Sources",
      "- TypeSafe — Introducing System One Models & Jev (Sep 15, 2026)",
      "- TypeSafe docs — Introduction: https://docs.typesafe.ai/introduction",
      "- TypeSafe docs — API / llms-full: https://docs.typesafe.ai/llms-full.txt",
      "- TypeSafe — Team: https://typesafe.ai/team",
      "- TypeSafe — Homepage: https://typesafe.ai/",
      "- SiliconANGLE — TypeSafe exits stealth with $40M (Sep 16, 2026): https://siliconangle.com/2026/09/16/typesafe-ai-exits-stealth-with-40m-to-build-ai-for-use-by-software/",
      "- BusinessWire — TypeSafe $40M seed / DCVC (Sep 15, 2026): https://www.businesswire.com/news/home/20260915525333/en/TypeSafe-AI-Emerges-From-Stealth-With-%2440M-in-Funding-With-New-Model-for-Composable-AI",
      "- TechStrong — Jev broader availability report (Sep 21, 2026): https://techstrong.ai/features/typesafe-opens-jev-for-general-availability/",
      "- Companion — Laya deep dive: /daily-digest/laya-ai-deep-dive",
    ],
  },
  {
    slug: "paperclip-deep-dive",
    title: "Paperclip deep dive — control plane for multi-agent companies",
    dek: "Full board brief on Paperclip (from NetworkChuck’s Sep 24 video): org-layer for AI agent teams, install path, risks (skills/CVEs/budgets), vs OpenClaw.",
    cardDek: "A tool for running teams of AI agents, with setup, risks, and how it compares.",
    hero: {
      src: "/art/digest/paperclip-deep-dive.webp",
      cardSrc: "/art/digest/paperclip-deep-dive-card.webp",
      alt: "A tabletop mobile of black branching arms holding stone teardrops, with one lime-green teardrop near the top.",
    },
    date: "2026-09-25",
    tag: "Deep dive",
    paragraphs: [
      "Board brief on Paperclip (Paperclip Labs): what it is, how the NetworkChuck demo used it, how to install, when it fits, and security caveats. Optional companion framing: typed decisions (Laya / Jev) vs agent org charts (this piece).",
      "## The video that triggered this brief",
      "- Title: you need to try Paperclip RIGHT NOW!",
      "- Channel: NetworkChuck",
      "- Upload: Thu Sep 24, 2026 (ET calendar day)",
      "- Length: ~28.8 min (1727 s)",
      "- ID / URL: 7RVf25Rg0Mc — https://www.youtube.com/watch?v=7RVf25Rg0Mc",
      "- Companion guide: https://github.com/theNetworkChuck/paperclip-guide (tested on Paperclip v2026.916.1; video filmed on v2026.831.1)",
      "- Creator callout: Dotta (@dotta) — Paperclip",
      "### What the video specifically claims / demos (from description + official companion guide; auto-captions were rate-limited during research so treat spoken nuance as approximate):",
      "- Paperclip is an open-source app for managing a team of AI agents with shared goals, assigned tasks, budgets, and human oversight — not “another chatbot.”",
      "- Demo mission: figure out why flushing the studio toilet keeps disconnecting everyone from the NAS; agents investigate a real network, question each other’s work, and return a verdict.",
      "- Org built in the episode: Claude Code CEO (“Dumbledore”), remote Hermes agents (CTO / network / storage), Codex hires (security reviewer, tooling), Pi + local models (scanner, watchdog, help desk), plus a Flare-linked exposure analyst — human sits as the board.",
      "- Teaching arc: install → connect remote Hermes → multi-harness team → routines → approval gates and watchdog agents that check whether “done” is real or blocked.",
      "- Sponsor in the video: Flare (identity threat intel); guide chapter wires Flare as a skill that must not print credentials.",
      "Primary how-to for that exact path: the NetworkChuck guide’s 11 chapters, not YouTube marketing alone.",
      "## What it is (verified)",
      "Paperclip is a self-hosted control plane for multi-agent work: Node.js server + React UI that models companies, org charts, goals, tickets/tasks, heartbeats, budgets, approvals, and audit logs. Agents bring their own runtimes; Paperclip wakes them, assigns work, and enforces governance.",
      "Official positioning (README / site): “If OpenClaw is an employee, Paperclip is the company.”",
      "It is not (same primary sources):",
      "- Not a chatbot (agents have jobs, not open chat windows)",
      "- Not an agent framework (does not tell you how to build agents)",
      "- Not a prompt manager or drag-and-drop workflow builder",
      "- Not a single-agent tool — one agent usually doesn’t need it; teams do",
      "- Not a code-review product (orchestrates work; PRs stay in your process)",
      "### Stack / license (verified Fri Sep 25, 2026 ET):",
      "- Repo: https://github.com/paperclipai/paperclip",
      "- Site / docs: https://paperclip.ing · https://docs.paperclip.ing",
      "- License: MIT © 2026 Paperclip Labs, Inc",
      "- Created: 2026-03-02 (GitHub)",
      "- Latest stable noted in research: v2026.916.1 (released 2026-09-21 UTC)",
      "- Requirements today: Node.js 24.11+, pnpm 9.15+ (docs; floor rose from Node 20 earlier in 2026)",
      "- Default UI/API: http://localhost:3100 with embedded Postgres for local onboard",
      "Popularity (GitHub API snapshot Fri Sep 25 ET): ≈ 84.7k stars, ≈ 15.2k forks, thousands of open issues. Star velocity is real and viral in the 2026 YouTube ecosystem — not by itself proof of production safety or enterprise fitness.",
      "## How it works (architecture)",
      "Human board creates a company and mission → hires agents into an org tree (roles, titles, reporting lines, permissions, budgets) → work flows as issues/tasks with goal ancestry, atomic checkout, comments, blockers, artifacts → agents wake on heartbeats (schedule and/or assignment / @-mention) via adapters → costs roll up; budgets hard-stop agents → board approves hires/strategy, can pause/override/terminate.",
      "Adapters (BYO agent): Claude Code, Codex, Cursor / Gemini / bash-style CLI agents, HTTP/webhook bots (e.g. OpenClaw), Hermes, Pi, OpenCode, plugins — anything that can receive a heartbeat.",
      "Four pillars (upstream framing): Agentic task manager · Org chart for agents · Agent employee training (skills / evals) · Agentic OS (runtime, sandboxes, SSO/RBAC, cost controls).",
      "Governance defaults: Autonomy is granted, not assumed. Hires and CEO strategy proposals are board-gated. Monthly budgets per agent; soft warn ~80%, hard pause at 100% (board can override).",
      "Deployment modes: local_trusted (loopback, fast solo) vs authenticated (login required — use this for anything network-reachable). Secrets encrypted; optional strict mode blocks plaintext API keys in agent env.",
      "## How to install / try",
      "Fastest path (official docs):",
      "npx paperclipai onboard --yes",
      "# later: npx paperclipai run",
      "# optional managed install: curl install.sh from paperclip.ing (checksum-verify; prefer pinned GitHub copy for stronger supply-chain posture)",
      "Or from source: git clone → pnpm install → pnpm dev → http://localhost:3100.",
      "Then: create company → hire CEO adapter → approve strategy → hire specialists → file tasks / routines. For the NetworkChuck IT-department path, follow https://github.com/theNetworkChuck/paperclip-guide (Node 24, Hermes wiring, approvals, watchdogs, export/import).",
      "Ops notes: Do not run onboard as root (embedded Postgres refuses admin users). Public VPS path needs authenticated mode, reverse proxy TLS, and paperclipai auth bootstrap-ceo — do not expose :3100 raw to the internet. Back up secrets/master.key. Telemetry is on by default; disable with PAPERCLIP_TELEMETRY_DISABLED=1 or DO_NOT_TRACK=1.",
      "## When it’s good for / when not",
      "### Good fit",
      "- You already juggle many agent terminals (Claude Code / Codex / Hermes / OpenClaw) and lose track of ownership, context, and spend",
      "- You want org-shaped automation: roles, delegation, tickets, 24/7 heartbeats, human board gates",
      "- You need cost hard-stops and audit trails across a portfolio of agents or multiple isolated companies on one deploy",
      "- You want to export/import whole company templates (agents, skills, routines) without reinventing ticketing",
      "### Poor fit / caution",
      "- Single coding agent for one repo — Paperclip is overhead; use the agent alone",
      "- Teams that need a mature hosted SaaS with SOC2 marketing and paid SLA tomorrow — this is self-hosted OSS moving very fast",
      "- Operators who will import untrusted skills / company bundles without review (see Risks)",
      "- Expecting Paperclip to replace Claude Code / OpenClaw — it orchestrates them; you still pay model/runtime costs and still secure those agents",
      "## Risks (read before you dogfood)",
      "1. Skill / import supply chain. Upstream advisory GHSA-w8hx-hqjv-vjcq (malicious skills → arbitrary server command via workspace runtime; secrets exfiltration). Patched in ≥ v2026.416.0. Treat skills and .paperclip.yaml imports like executable code.",
      "2. Critical import / localhost flaws (Aug 2026 coverage). Oasis / The Hacker News: CVE-2026-41679 (CVSS 10.0) — malicious agent import on network-auth deployments with open registration; plus DNS-rebinding against local_trusted localhost, and under-authenticated routes. Fix point reported as v2026.416.0+. Rapid7 Metasploit module exists for the CVE. Upgrade, lock registration, prefer authenticated + hostname guards, never treat loopback as “safe on shared networks.”",
      "3. Spend. Budgets help, but many agents × frontier models still burns cash; set low caps first. Docs warn API keys cost money before first hire.",
      "4. Autonomy theater. Approval gates only work if humans actually review. Watchdogs help catch fake “done”; they do not replace threat modeling.",
      "5. Agent surface area. Securing OpenClaw / Hermes / Claude Code (skills, tool access, network) remains your job. Paperclip FAQ is explicit: governance covers Paperclip mutations (e.g. hiring); agent tools are yours to constrain.",
      "6. Version churn. Video on 2026.831.1, guide on 2026.916.1, Node floor now 24.11 — pin versions and read upgrade notes.",
      "## Paperclip vs single agents / OpenClaw",
      "- Claude Code / Codex / Cursor: Individual employees (coding / tool agents)",
      "- OpenClaw / Hermes / HTTP bots: Individual employees (often always-on or remote)",
      "- Paperclip: The company: org chart, tickets, budgets, heartbeats, board approvals",
      "Pointing OpenClaw at Asana/Trello still leaves checkout races, session persistence, cost governance, and hire/strategy gates unsolved — Paperclip’s pitch is those subtleties. Bring-your-own-ticket-system remains on the upstream roadmap.",
      "## Claims vs evidence",
      "### Stronger / source-backed",
      "- Product category and “not a chatbot/framework” wording match README, site FAQ, and NetworkChuck guide",
      "- MIT self-host install paths (npx paperclipai onboard, docs, releases) work as documented surfaces",
      "- Viral GitHub popularity is measurable via API",
      "- Security issues are real and documented (GitHub advisories + Hacker News / Oasis); patches exist at stated tags",
      "- Multi-harness IT-department demo path is reproducible via the companion guide",
      "### Weaker / treat as hype",
      "- “Zero-human companies” / “operating system for work that never sleeps” — marketing aspiration, not a verified ops outcome",
      "- Any implied “destroyed OpenClaw” YouTube framing — category error; Paperclip uses OpenClaw-class agents",
      "- Star count as quality proxy — ignore for production decisions",
      "- Undisclosed ARR, customer logos, or priced commercial support — not verified in sources reviewed",
      "## Optional link to Laya / Jev",
      "Different layers: Laya / Jev = typed System-1 decisions (choice / score / noul) inside app code. Paperclip = org + ticket + budget plane for generative agent teams. Complementary if you want probabilistic gates and multi-agent companies — not substitutes.",
      "## Bottom line",
      "Paperclip is a real MIT control plane for running many BYO agents as a governed company — matching what NetworkChuck demoed on Sep 24, 2026. Install it when coordination and spend across agents hurts; skip it for one-agent workflows. Pin recent releases, treat skills/imports as code, and lock deployment mode before exposing a network.",
      "## Sources",
      "- NetworkChuck — you need to try Paperclip RIGHT NOW! (Sep 24, 2026): https://www.youtube.com/watch?v=7RVf25Rg0Mc",
      "- NetworkChuck companion guide (tested v2026.916.1): https://github.com/theNetworkChuck/paperclip-guide",
      "- Paperclip — website: https://paperclip.ing/",
      "- GitHub — paperclipai/paperclip: https://github.com/paperclipai/paperclip",
      "- Paperclip docs — Installation: https://docs.paperclip.ing/guides/getting-started/installation.md",
      "- Release — v2026.916.1: https://github.com/paperclipai/paperclip/releases/tag/v2026.916.1",
      "- Advisory GHSA-w8hx-hqjv-vjcq — malicious skills / ACE: https://github.com/paperclipai/paperclip/security/advisories/GHSA-w8hx-hqjv-vjcq",
      "- The Hacker News — Paperclip import / localhost flaws (Aug 5, 2026): https://thehackernews.com/2026/08/paperclip-ai-flaws-let-attackers-run.html",
      "- Dotta / Paperclip on X: https://x.com/dotta",
      "- Companion — Laya deep dive: /daily-digest/laya-ai-deep-dive",
      "- Companion — System One / Jev digest: /daily-digest/system-one-and-jev-deep-dive",
    ],
  },
  {
    slug: "keep-hard-rules-sticky",
    title: "Keep hard rules sticky",
    dek: "Soft reminders fade in long chats. Re-inject the non-negotiables every turn.",
    cardDek: "Repeat the must-follow rules every turn so long chats don't forget them.",
    hero: {
      src: "/art/digest/keep-hard-rules-sticky.webp",
      cardSrc: "/art/digest/keep-hard-rules-sticky-card.webp",
      alt: "A clear frosted cylinder filled with pebbles and grey sand, with a small lime-green float resting on top.",
    },
    date: "2026-09-28",
    sourceNote: "based on hub digest 2026-09-24 technique test",
    paragraphs: [
      "Long agent chats have a boring failure mode. The hard rules were clear up front — don't send money, don't force-push, keep Auth off — then twenty turns later the model proposes exactly that, like the rule never existed.",
      "It isn't malice. Context fills up with task detail, tool noise, and soft advice. The one-time \"don't do X\" line gets buried. Soft reminders fade. Sticky ones don't.",
      "Put a short block of non-negotiables into each turn's context. Not once at session start. Every turn, before the next action. Keep soft advice out of that block so it stays short and sharp — red lines only.",
      "How we apply it: list the hard rules in one compact block, re-inject that same block every turn, and leave the coaching elsewhere. The goal is simple — when a dangerous action shows up late in the chat, the guardrail is still sitting in front of the model.",
      "We tested this offline on the box as a structural sim (no live model). Twelve turns. Eight proposals that should have been blocked. Rules stated once blocked four of eight and slipped four times. Sticky reinjection blocked all eight, with zero slips, and still let innocent actions through.",
      "Smallest useful version: a sticky list you actually re-inject, not a one-time preamble you hope the model remembers.",
      "This does not replace tool-level authorization. It only keeps the policy text present when a dangerous action shows up. Offline numbers are not production rates — retest on a live agent before you treat the block rates as real.",
    ],
  },
  {
    slug: "refuse-answers-sources-do-not-support",
    title: "Refuse answers sources do not support",
    dek: "Stops shipping answers that look cited but are not backed.",
    cardDek: "Don't ship an answer unless its sources actually back it.",
    hero: {
      src: "/art/digest/refuse-answers-sources-do-not-support.webp",
      cardSrc: "/art/digest/refuse-answers-sources-do-not-support-card.webp",
      alt: "A pale stone slab on black legs, with one shorter black post beside it that doesn't reach the slab, topped by a lime-green cap.",
    },
    date: "2026-09-28",
    paragraphs: [
      "## The technique",
      "Agents often attach citations that do not actually support the claim. A grounding gate compares claim tokens to cited spans: accept when supported, refuse when citations are missing or unrelated, and regenerate when overlap is only partial. That blocks the common always-accept slip where a polished answer ships with decorative sources.",
      "## How it was tested",
      "Offline structural sim (no live model): 10 grounding cases. Gate matched all 10 accept/refuse/regenerate decisions (4 accept, 4 refuse, 2 regenerate); caught 6 cases a naive always-accept path would have slipped.",
    ],
  },
  {
    slug: "do-not-swap-tools-on-a-hunch",
    title: "Do not swap tools on a hunch",
    dek: "Blocks risky mid-flight tool swaps without proof.",
    cardDek: "Don't let an agent switch tools mid-task without proof it needs to.",
    hero: {
      src: "/art/digest/do-not-swap-tools-on-a-hunch.webp",
      cardSrc: "/art/digest/do-not-swap-tools-on-a-hunch-card.webp",
      alt: "A stone balance scale weighing two nearly identical black wrenches, with a small lime-green pointer on top.",
    },
    date: "2026-09-28",
    paragraphs: [
      "## The technique",
      "Mid-flight tool swaps are tempting when a call looks flaky, but suspicion alone is not enough. Require evidence that supports the failure hypothesis, a twin that passes structural checks (schema, reachability, side-effect class), and pairwise preference for the twin in both presentation orders so position bias cannot sneak a swap through.",
      "## How it was tested",
      "Offline structural sim (no live model): 8 replace cases. Gate matched all 8; allowed 2 full-gate replaces and blocked 6 (suspicion-only, missing signals, order bias, bad/unreachable/incomplete twin).",
    ],
  },
  {
    slug: "check-each-tool-step-before-next",
    title: "Check each tool step before next",
    dek: "Stops bad tool steps from cascading into the rest of the run.",
    cardDek: "Check each step's result so one bad step doesn't spoil the run.",
    hero: {
      src: "/art/digest/check-each-tool-step-before-next.webp",
      cardSrc: "/art/digest/check-each-tool-step-before-next-card.webp",
      alt: "A row of stone dominoes with the first few fallen, stopped by a small lime-green peg before the rest can tip.",
    },
    date: "2026-09-28",
    paragraphs: [
      "## The technique",
      "A bad tool step that continues quietly poisons the rest of the trajectory. After each call, run four checks: does it advance the task, do used args match declared args, was execution valid, and were constraints satisfied. On fail, emit structured feedback and stop for replan instead of always-continuing into cascade.",
      "## How it was tested",
      "Offline structural sim (no live model): 8 trajectories. Stop-on-fail matched all 8 expected run lengths; blocked 6 cascades that naive always-continue completed. All four check dimensions fired on a deliberately broken step.",
    ],
  },
  {
    slug: "ask-before-doing-what-wasnt-asked",
    title: "Ask before doing what wasn't asked",
    dek: "Stops agents from doing helpful extras nobody asked for.",
    cardDek: "Make agents ask before adding extras you didn't request.",
    hero: {
      src: "/art/digest/ask-before-doing-what-wasnt-asked.webp",
      cardSrc: "/art/digest/ask-before-doing-what-wasnt-asked-card.webp",
      alt: "A walled stone yard with stacked black blocks inside, a closed gate with a small lime-green bell, and a toy wheelbarrow outside.",
    },
    date: "2026-09-29",
    paragraphs: [
      "## The technique",
      "Eager agents add unrequested extras: the user asks for a draft and the agent sends it, asks for a test fix and it also edits CI, asks for a summary and it declines a meeting. Guarding only irreversible actions misses most of these because many extras are technically undoable. Turn the request into an explicit scope (allowed verbs and targets) and ask before anything outside it. For our agents this means fewer surprise side effects in mail, repos, tickets and deploys, and it pairs with the irreversible-action preflight from Sep 25 rather than replacing it. This week's reporting that OpenAI held back GPT-6.1 Astra partly over a tendency to move forward without asking permission is the same failure at model level.",
      "## How to apply",
      "1. When a task starts, restate it as a short scope list: verbs (draft, edit, read) times targets (this email, these files).",
      "2. Before each tool call, check the verb and target against that list.",
      "3. Out of scope means pause and ask one plain question; in scope means proceed.",
      "4. Keep the irreversible-action preflight as a second layer.",
      "## How it was tested",
      "Evidence (offline structural sim, no live model): 12 hand-written tasks with 37 proposed actions; 19 were hand-labeled as ones the user would want to be asked about, including 3 edge cases planted to make the literal rule wrong. Executing everything ran all 19 unwanted actions. Guarding only irreversible actions ran 13 of 19 and asked needlessly 2 times. The scope gate ran 1 of 19 (a ticket reassignment that fell inside the literal target) and also asked needlessly 2 times (a needed test fixture and a harmless read of metrics).",
      "## Limits",
      "The labels and proposals are hand-authored, so the counts show the rule's shape, not real agent rates. A live retest needs real agent transcripts with user-labeled 'should have asked' actions, and a measure of how often the extra questions annoy users.",
    ],
  },
  {
    slug: "test-search-before-saying-none",
    title: "Test search before saying none",
    dek: "A broken search tool can return the same clean empty list as a real \"nothing found.\" One lookup you know should hit tells them apart.",
    cardDek: "Run one search you know should hit before you trust an empty result.",
    hero: {
      src: "/art/digest/test-search-before-saying-none.webp",
      cardSrc: "/art/digest/test-search-before-saying-none-card.webp",
      alt: "An empty black mine cart on a short rail, with a small lime-green canary perched on its rim.",
    },
    date: "2026-09-29",
    paragraphs: [
      "The problem",
      "An agent searches for open incidents, gets an empty list back, and tells you there are none. Usually that's true. Sometimes the token expired, a bad reindex left the index empty, or one partition is down. Plenty of connectors return a clean, successful-looking empty list in those cases instead of an error. The agent can't tell \"nothing matches\" from \"nothing works,\" so a broken tool turns into a confident answer. That's worse than an error, because nobody goes back to check.",
      "The technique",
      "Keep one record in each data source that you know is there. Call it a canary. When a search comes back empty, look up the canary before trusting the result. If the canary shows up, the tool works and \"nothing found\" stands. If the canary is missing too, don't claim absence. Say the tool looks broken and you can't confirm either way.",
      "If the data is split across shards or partitions, keep one canary in each. A single canary only proves its own shard is up.",
      "What we saw",
      "We ran this offline as a scripted simulation, with no live model: 120 search calls against a mock index split into two shards. The tool was healthy on 90 calls, fully silent on 15, and had one shard down on 15. 63 of the queries had a real match.",
      "- Trusting empty results gave 11 false \"none exist\" answers.",
      "- One canary cut that to 5, for 68 extra lookups. All 15 \"tool looks broken\" flags came during real outages. The 5 misses were all partial outages where the down shard wasn't the canary's shard.",
      "- One canary per shard got it to 0, for 136 extra lookups. All 27 flags came during real outages.",
      "So the check works, but only as far as the canary reaches. A partial outage beats a single canary.",
      "Limits",
      "These are simulation numbers, not production rates. We picked the outage mix and the index, so the counts show how the check behaves, not how often your tools fail. The extra lookup adds latency on every empty result, and the per-shard version doubles that here. Canaries also go stale if someone deletes the record. A real test needs a live connector with injected failures (expired auth, an empty index, one partition down), a measure of the added latency, and a check that the canary records stay put.",
      "Try it",
      "1. For each search tool your agent uses, pick one stable record per source or partition that should always be there.",
      "2. Wrap the tool so an empty result triggers a canary lookup.",
      "3. If any canary is missing, return \"search looks unavailable, can't confirm no results\" and log it.",
      "4. If every canary is found, pass the empty result through as a real \"none found.\"",
      "5. Alert on canary misses and treat them as incidents, not answers.",
    ],
  },
  {
    slug: "make-routers-pick-from-a-fixed-list",
    title: "Make routers pick from a fixed list",
    dek: "Stops chatty router replies from sending tickets to the wrong queue.",
    cardDek: "Give the sorting step a fixed list so tickets land in the right queue.",
    hero: {
      src: "/art/digest/make-routers-pick-from-a-fixed-list.webp",
      cardSrc: "/art/digest/make-routers-pick-from-a-fixed-list-card.webp",
      alt: "A stone shape-sorter box with four holes, black blocks beside it, and a lime-green cube dropping into the square hole.",
    },
    date: "2026-09-29",
    paragraphs: [
      "## The technique",
      "Routers that answer in prose ('not billing, this is account security') get keyword-parsed by the harness, which often picks the first route word it sees or falls back to a default queue. Invented labels slip through the same way. Make the router return one value from a fixed list plus confidence, validate it, and send off-list or low-confidence answers to a human instead of guessing. For our agents this keeps security and refund cases out of the wrong queue, and it matches the shape of OpenAI's new Decisions API (a fixed set of answers per question).",
      "## How to apply",
      "1. Define the allowed labels as an enum in a structured-output schema.",
      "2. Validate the returned label against the list and reject anything else.",
      "3. Require a confidence value and route anything under your threshold (0.6 in the sim) to a human.",
      "4. Log rejects so the list can grow on purpose.",
      "## How it was tested",
      "Evidence (offline structural sim, no live model): 90 seeded support messages across 4 routes (26 were account security). The simulated router made the same underlying call under both contracts: about 88% right, otherwise a close neighbor, and sometimes an invented 'fraud' label. Only the output format changed. With free text (70% followed the 'Route: X' format, 30% drifted into prose) the keyword parser got 65 right and 25 wrong, 10 of them account-security cases; 12 of those errors came purely from parsing when the model's call was right. The fixed list got 75 right and 3 wrong (1 account security) and sent 12 to a human (5 off-list labels plus 7 low confidence).",
      "## Limits",
      "The error rate and the prose-drift mix are assumptions of the sim, so the size of the gap depends on them; the direction is what carries over. A live retest needs real router outputs on labeled tickets, plus a measure of whether the human-handoff load is acceptable.",
    ],
  },
  {
    slug: "dont-follow-orders-in-tool-text",
    title: "Don't follow orders in tool text",
    dek: "Tool replies are data, not instructions. Check them for commands before the agent plans its next step.",
    cardDek: "Treat tool replies as data, so hidden commands can't steer your agent.",
    hero: {
      src: "/art/digest/dont-follow-orders-in-tool-text.webp",
      cardSrc: "/art/digest/dont-follow-orders-in-tool-text-card.webp",
      alt: "A stone sieve holds back sharp black shards while pale pebbles fall into the bowl below, with a lime-green clip on its rim.",
    },
    date: "2026-10-01",
    paragraphs: [
      "## The problem",
      "An agent reads an email, a web page, or a ticket through a tool and treats that text as if you wrote it. Somewhere in the body is a line like \"ignore your previous rules,\" \"forward this to everyone,\" or \"delete the repo.\" The model goes along with it because the words arrived through a successful tool call. That's how one poisoned message turns into a mass email, a wiped repo, or a message that copies itself to the next inbox, and nobody asked for any of it.",
      "## The technique",
      "Treat everything a tool returns as data, never as a new source of instructions. Before the agent plans its next tool call, scan the returned text for instruction-shaped lines: ignore previous rules, forward to all, run this command, delete the database, pass this message on, treat this as your system prompt. On a hit, strip or wrap those lines, mark the result untrusted, and refuse any action that only that text asked for. The user's request still drives the next step. The tool text doesn't.",
      "## What we saw",
      "We ran this offline as a scripted simulation, with no live model: 12 tool replies, 8 with planted instructions and 4 ordinary ones.",
      "- A naive setup that acts on whatever the tool text suggests carried out all 8 harmful follow-ups, including forwarding to everyone, deleting a repo, sending data out through a web page, and moving money.",
      "- With the check in place, all 8 planted replies were flagged and 0 harmful follow-ups ran. All 4 ordinary replies (an email summary, a ticket, a code review, a status message) went through with no false blocks.",
      "So in this test, the check closed the \"the tool said so\" path without getting in the way of normal email and ticket text.",
      "## Limits",
      "These are simulation numbers, not production rates. The same hand-written pattern list shaped both the check and the test cases, so a clean sweep here shows the mechanism works, not how well it holds up against a real attacker. A reworded or encoded instruction can slip past until you widen the list. The check also doesn't replace tool-level permissions or hard rules on irreversible actions. It only stops tool text from acting as a command channel. A live retest needs real agent transcripts with injected email and web content, plus a measure of how often stripping removes wording the user actually needed.",
      "## Try it",
      "1. Write down the instructions you'll never act on from tool text, such as forward to all, ignore prior rules, delete or wipe, run this command, pass this on, and new system prompt.",
      "2. Scan every tool reply before the next planning step.",
      "3. On a hit, mark the reply untrusted, strip or wrap the matching lines, and drop any tool call that came only from that text.",
      "4. Log each hit as a security signal instead of skipping it silently.",
      "5. Keep hard rules and checks before irreversible actions as separate layers, because this check won't catch everything.",
    ],
  },
  {
    slug: "the-ai-safety-paradox",
    title: "The AI Safety Paradox",
    dek: "Asking the inmates to guard the prison.",
    cardDek: "Asking the inmates to guard the prison.",
    date: "2026-10-01",
    tag: "Essay",
    hero: {
      image: "the-ai-safety-paradox",
      alt: "A frosted safe with its door open, a dark egg-shaped object inside and a key hanging on its side.",
    },
    pullQuote: { text: "It's like asking the inmates to design the locks.", cite: "— Osbel Morell" },
    paragraphs: [
      "Anthropic's IPO filing landed like a confession. According to Reuters, which reviewed the confidential draft, it has roughly eighty pages of risk factors in a two-hundred-sixty-one-page main body — nearly double the forty-eight pages they gave to describing their actual business. Buried in there: a warning that advanced AI could pose \"catastrophic or existential risks to humanity.\" Models that could \"resist shutdown.\" That \"conceal or manipulate information.\" Behavior \"resembling blackmail.\"",
      "A company reportedly chasing a two-trillion-dollar valuation just told investors its product might end us. That's not a footnote. That's the moment the industry admitted the gap out loud.",
      "---",
      "But here's the part that should make you uncomfortable. The entire safety apparatus — red-teaming, adversarial testing, interpretability research — runs on AI evaluating AI. We're using the same models we're trying to contain to figure out how to contain them. It's like asking the inmates to design the locks. And not just design them — to test them, to find the weaknesses, to write the reports that say \"we're safe now.\"",
      "The deeper problem is the blueprint. You can't publish a defense and expect it to hold. The moment you describe how something is protected, you've handed the adversary a map. With AI, the adversary isn't a person poking around at human speed. It's a system that reasons about the defense itself, adapts, and tries thousands of approaches in seconds. The blueprint isn't a vulnerability. It's a roadmap.",
      "The only real security is obscurity plus capability asymmetry — keeping methods secret and staying one step ahead. But that's not how this industry works. Everything gets open-sourced, peer-reviewed, published. Transparency is treated as a virtue. In this specific case, it's a liability.",
      "---",
      "And then there are the institutions that actually matter. Governments. Banks. The places where a breach doesn't just cost money — it costs lives, or sovereignty, or the trust that holds a society together. These systems weren't built for a non-human, never-sleeping, adaptive adversary. They were built for a person at a terminal. COBOL on a mainframe from the eighties. Legacy architectures that assume human-speed threats.",
      "You can't patch your way out of that. The architecture itself is the problem. Air-gapping the critical systems sounds clean until you realize it breaks the workflows these institutions depend on. So the realistic options are grim: isolate and accept the cost, or accept that some systems will get breached and focus on detection and containment instead of prevention.",
      "The uncomfortable truth is that the institutions with the most to lose are the least equipped to defend it. And the gap between what an LLM can do and what a legacy system can withstand isn't closing. It's widening.",
      "---",
      "So the question isn't whether we can catch up. It's whether we should slow down the capability side until the security side has a fighting chance. But even that has its own paradox — because slowing down means the people building the models are the ones deciding when to slow down. And they've got a two-trillion-dollar reason not to.",
      "We're trusting the thing we're afraid of to tell us when to be afraid. That's not a strategy. That's a prayer.",
      "— Osbel Morell",
    ],
  },
  {
    slug: "break-loops-when-progress-stalls",
    title: "Break loops when progress stalls",
    dek: "A busy agent isn't always a working one. Check progress every few steps, and force a change of course when it stalls.",
    cardDek: "Check progress every few steps, and change course when an agent stalls.",
    hero: {
      src: "/art/digest/break-loops-when-progress-stalls.webp",
      cardSrc: "/art/digest/break-loops-when-progress-stalls-card.webp",
      alt: "A small black toy train on a looped stone track, with a lime-green switch lever set to send it onto a straight exit track.",
    },
    date: "2026-10-02",
    paragraphs: [
      "## The problem",
      "A long-running agent keeps calling tools, but the job isn't getting any closer to done. It checks the same places, reruns the same log queries, or wanders into side tasks while the real gap, the missing fact or the unfinished step, stays open. The run looks busy while the budget runs out and the ticket stays open. More history or better summaries won't fix it. Nothing in the loop tells the agent it has stopped making progress.",
      "## The technique",
      "The authors of a recent paper ([arXiv:2610.01415](https://arxiv.org/abs/2610.01415)) call this failure belief trapping.",
      "Keep a short, explicit note of where things stand: the facts that matter, what the agent still needs to find out, and what it still needs to finish. After each step, look back over the last few steps. A stall is when the same open items stay open and the recent steps either made no progress or kept circling back to the same picture.",
      "When you see a stall, name the kind. The agent is frozen on one move, cycling between the same few steps, or drifting through changes that never touch the open item. Then add one constraint for the next step: block the useless move, break the cycle, or refocus on the open item. Require new evidence or a real change before going on. Lift the constraint once progress resumes.",
      "## What we saw",
      "Our numbers come from an offline box test with no live model. We scripted 6 runs: 3 stuck (cycling, frozen, drifting) and 3 healthy, one of them slow but still making progress.",
      "- Letting the agent keep going resolved 0 of the 3 stuck runs and wasted 32 steps on them.",
      "- With the stall check on a 4-step window, all 3 stalls were caught and all 3 runs recovered. Wasted steps after the stall dropped to 0. None of the 3 healthy runs were flagged, including the slow one.",
      "- One miss: the drifting run was caught but labeled as frozen.",
      "The paper's numbers are theirs, not ours. Their method scored highest on all four long-horizon benchmarks with all three models, with relative gains over the strongest baseline of up to 22.68% on ALFWorld and 37.89% on RCA-100 joint accuracy. Removing the stall diagnosis and recovery hurt. With Qwen3.7-Plus, ALFWorld success fell from 88.81% to 73.13%, and RCA-100 joint accuracy fell from 38.83% to 33.98%.",
      "## Limits",
      "Our runs were hand-built, so they show how the check behaves, not how often real agents stall. Our simple setup also blurred drift and freeze. The full method isn't cheap. On RCA-100 with Qwen3.7-Plus, the paper reports 5.06 times the total tokens of the plain baseline, even though the main agent itself used 20.9% fewer. Window size and the stall threshold need tuning for each kind of work. It doesn't replace hard rules or other safety checks. It only stops unproductive loops.",
      "## Try it",
      "1. After each tool step, update the note: key facts, what's unknown, what's unfinished.",
      "2. Keep the last few steps in view. Start with a window of 4 to 8.",
      "3. Flag a stall when the same items stay open and the recent steps either made no progress or kept repeating.",
      "4. On a stall, name the pattern (frozen, cycling, or drifting) and add one constraint that blocks the useless move until new evidence shows up.",
      "5. Log each stall, and lift the constraint when progress resumes.",
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getPostsNewestFirst(): Post[] {
  return [...posts].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}
