import type { ChangeEvent } from "./types";

/** Anchor "now" so demos stay stable; roughly matches ship day 2026-09-16. */
const NOW = new Date("2026-09-16T10:00:00.000Z").getTime();

function ago(hours: number): string {
  return new Date(NOW - hours * 60 * 60 * 1000).toISOString();
}

/** Realistic change events for api / web / workers over the last week. */
export const SAMPLE_EVENTS: ChangeEvent[] = [
  // —— api (rich 24h window) ——
  {
    id: "e-api-d1",
    service: "api",
    kind: "deploy",
    ts: ago(3),
    version: "1.48.2",
    sha: "a3f91c2",
    env: "production",
    by: "maya@acme.io",
    note: "Hotfix: rate-limit header leak",
  },
  {
    id: "e-api-c1",
    service: "api",
    kind: "config",
    ts: ago(4.5),
    key: "RATE_LIMIT_RPM",
    oldValue: "600",
    newValue: "900",
    by: "ops-bot",
  },
  {
    id: "e-api-f1",
    service: "api",
    kind: "flag",
    ts: ago(6),
    flag: "checkout_v2",
    fromState: "10%",
    toState: "50%",
    by: "jordan@acme.io",
  },
  {
    id: "e-api-u1",
    service: "api",
    kind: "upstream",
    ts: ago(8),
    dependency: "payments-gateway",
    status: "degraded",
    depVersion: "2026.09.12",
    note: "Elevated 429s from Stripe mirror",
  },
  {
    id: "e-api-d2",
    service: "api",
    kind: "deploy",
    ts: ago(18),
    version: "1.48.1",
    sha: "9be2201",
    env: "production",
    by: "ci-bot",
  },
  {
    id: "e-api-c2",
    service: "api",
    kind: "config",
    ts: ago(20),
    key: "FEATURE_CACHE_TTL_SEC",
    oldValue: "60",
    newValue: "30",
    by: "sre-oncall",
  },
  {
    id: "e-api-f2",
    service: "api",
    kind: "flag",
    ts: ago(30),
    flag: "graphql_persisted_queries",
    fromState: "off",
    toState: "on",
    by: "platform",
  },
  {
    id: "e-api-d3",
    service: "api",
    kind: "deploy",
    ts: ago(52),
    version: "1.48.0",
    sha: "71cd004",
    env: "production",
    by: "maya@acme.io",
  },
  {
    id: "e-api-u2",
    service: "api",
    kind: "upstream",
    ts: ago(70),
    dependency: "auth-service",
    status: "healthy",
    depVersion: "4.2.0",
    note: "Rolled forward after cert rotate",
  },
  {
    id: "e-api-c3",
    service: "api",
    kind: "config",
    ts: ago(96),
    key: "LOG_LEVEL",
    oldValue: "info",
    newValue: "debug",
    by: "sre-oncall",
  },
  {
    id: "e-api-d4",
    service: "api",
    kind: "deploy",
    ts: ago(120),
    version: "1.47.5",
    sha: "e0aa91f",
    env: "staging",
    by: "ci-bot",
  },

  // —— web ——
  {
    id: "e-web-d1",
    service: "web",
    kind: "deploy",
    ts: ago(5),
    version: "3.12.0",
    sha: "c88e441",
    env: "production",
    by: "alex@acme.io",
  },
  {
    id: "e-web-f1",
    service: "web",
    kind: "flag",
    ts: ago(7),
    flag: "new_nav",
    fromState: "off",
    toState: "25%",
    by: "product",
  },
  {
    id: "e-web-c1",
    service: "web",
    kind: "config",
    ts: ago(12),
    key: "CDN_CACHE_BUST",
    oldValue: "v41",
    newValue: "v42",
    by: "ci-bot",
  },
  {
    id: "e-web-u1",
    service: "web",
    kind: "upstream",
    ts: ago(14),
    dependency: "api",
    status: "healthy",
    depVersion: "1.48.2",
    note: "Client bumped base URL pin",
  },
  {
    id: "e-web-d2",
    service: "web",
    kind: "deploy",
    ts: ago(40),
    version: "3.11.4",
    sha: "55ab902",
    env: "production",
    by: "ci-bot",
  },
  {
    id: "e-web-f2",
    service: "web",
    kind: "flag",
    ts: ago(80),
    flag: "dark_mode_default",
    fromState: "off",
    toState: "on",
    by: "design",
  },

  // —— workers ——
  {
    id: "e-wk-d1",
    service: "workers",
    kind: "deploy",
    ts: ago(2),
    version: "0.9.8",
    sha: "f1d22aa",
    env: "production",
    by: "platform",
  },
  {
    id: "e-wk-c1",
    service: "workers",
    kind: "config",
    ts: ago(2.5),
    key: "QUEUE_CONCURRENCY",
    oldValue: "8",
    newValue: "16",
    by: "sre-oncall",
  },
  {
    id: "e-wk-u1",
    service: "workers",
    kind: "upstream",
    ts: ago(9),
    dependency: "redis-jobs",
    status: "healthy",
    depVersion: "7.2",
    note: "Failover drill complete",
  },
  {
    id: "e-wk-f1",
    service: "workers",
    kind: "flag",
    ts: ago(22),
    flag: "batch_email_v3",
    fromState: "canary",
    toState: "100%",
    by: "growth",
  },
  {
    id: "e-wk-d2",
    service: "workers",
    kind: "deploy",
    ts: ago(60),
    version: "0.9.7",
    sha: "88cc110",
    env: "production",
    by: "ci-bot",
  },
  {
    id: "e-wk-c2",
    service: "workers",
    kind: "config",
    ts: ago(100),
    key: "DLQ_RETRY_MAX",
    oldValue: "3",
    newValue: "5",
    by: "ops-bot",
  },
];

export const SAMPLE_ANCHOR_ISO = new Date(NOW).toISOString();
